version: '3.8'

services:
  # PostgreSQL Database only
  postgres:
    image: pgvector/pgvector:pg16
    container_name: promtitude-postgres
    environment:
      POSTGRES_USER: promtitude
      POSTGRES_PASSWORD: promtitude123
      POSTGRES_DB: promtitude
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U promtitude"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache only
  redis:
    image: redis:7-alpine
    container_name: promtitude-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant Vector Database only
  qdrant:
    image: qdrant/qdrant
    container_name: promtitude-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: INFO

volumes:
  postgres_data:
  redis_data:
  qdrant_data: