[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql", "libpq"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONUNBUFFERED = "1"
PYTHON_VERSION = "3.11"