'use client';

import Link from 'next/link';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <Link href="/" className="text-blue-600 hover:text-blue-800 dark:text-blue-400 mb-8 inline-block">
          ← Back to Home
        </Link>
        
        <h1 className="text-4xl font-bold mb-8 text-gray-900 dark:text-white">Terms of Service</h1>
        
        <div className="prose prose-lg dark:prose-invert max-w-none">
          <p className="text-gray-600 dark:text-gray-400 mb-6">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">1. Agreement to Terms</h2>
            <p className="text-gray-700 dark:text-gray-300">
              By accessing or using Promtitude's services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing our services.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">2. Description of Service</h2>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              Promtitude provides an AI-powered recruitment platform that includes:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 dark:text-gray-300">
              <li>Natural language candidate search</li>
              <li>Resume parsing and analysis</li>
              <li>AI Interview Copilot with live transcription</li>
              <li>Automated outreach message generation</li>
              <li>Analytics and reporting tools</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">3. User Accounts</h2>
            <p className="text-gray-700 dark:text-gray-300 mb-4">To use our services, you must:</p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 dark:text-gray-300">
              <li>Be at least 16 years old</li>
              <li>Provide accurate and complete registration information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized use</li>
              <li>Be responsible for all activities under your account</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">4. Acceptable Use</h2>
            <p className="text-gray-700 dark:text-gray-300 mb-4">You agree NOT to:</p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 dark:text-gray-300">
              <li>Use the service for any illegal or unauthorized purpose</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Upload malicious code or interfere with service operation</li>
              <li>Attempt to gain unauthorized access to any part of the service</li>
              <li>Harass, abuse, or harm other users</li>
              <li>Use automated systems to access the service without permission</li>
              <li>Resell or redistribute the service without authorization</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">5. Content and Data</h2>
            
            <h3 className="text-xl font-medium mb-3 text-gray-800 dark:text-gray-200">5.1 Your Content</h3>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              You retain ownership of all content you upload (resumes, notes, etc.). By uploading content, you grant us a license to use, store, and process it to provide our services. You are responsible for ensuring you have the right to upload and use any content.
            </p>

            <h3 className="text-xl font-medium mb-3 text-gray-800 dark:text-gray-200">5.2 AI-Generated Content</h3>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              Content generated by our AI (interview questions, outreach messages, etc.) is provided "as-is". You are responsible for reviewing and modifying AI-generated content before use. We do not guarantee the accuracy or appropriateness of AI-generated content.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">6. Privacy and Data Protection</h2>
            <p className="text-gray-700 dark:text-gray-300">
              Your use of our services is also governed by our Privacy Policy. By using Promtitude, you acknowledge that you have read and understood our Privacy Policy and agree to the collection and use of information as described therein.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">7. Payment Terms</h2>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              If you subscribe to a paid plan:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 dark:text-gray-300">
              <li>Payments are processed securely through third-party providers</li>
              <li>Subscriptions auto-renew unless cancelled</li>
              <li>Refunds are provided according to our refund policy</li>
              <li>You are responsible for all applicable taxes</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">8. Intellectual Property</h2>
            <p className="text-gray-700 dark:text-gray-300">
              The Promtitude platform, including its design, features, and content (excluding user content), is owned by us and protected by intellectual property laws. You may not copy, modify, or reverse engineer any part of our service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">9. Third-Party Services</h2>
            <p className="text-gray-700 dark:text-gray-300">
              Our service integrates with third-party services (LinkedIn, OpenAI, etc.). Your use of these integrations is subject to their respective terms of service. We are not responsible for third-party services or content.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">10. Disclaimers</h2>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE SPECIFICALLY DISCLAIM:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-700 dark:text-gray-300 uppercase">
              <li>WARRANTIES OF MERCHANTABILITY</li>
              <li>FITNESS FOR A PARTICULAR PURPOSE</li>
              <li>NON-INFRINGEMENT</li>
              <li>ACCURACY OR RELIABILITY OF RESULTS</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">11. Limitation of Liability</h2>
            <p className="text-gray-700 dark:text-gray-300">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, PROMTITUDE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR GOODWILL.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">12. Indemnification</h2>
            <p className="text-gray-700 dark:text-gray-300">
              You agree to indemnify and hold harmless Promtitude and its officers, directors, employees, and agents from any claims, damages, or expenses arising from your use of the service or violation of these terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">13. Termination</h2>
            <p className="text-gray-700 dark:text-gray-300">
              We may terminate or suspend your account immediately, without prior notice, for any reason, including breach of these Terms. Upon termination, your right to use the service will cease immediately.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">14. Governing Law</h2>
            <p className="text-gray-700 dark:text-gray-300">
              These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions. Any disputes shall be resolved in the courts of Bangalore, India.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">15. Changes to Terms</h2>
            <p className="text-gray-700 dark:text-gray-300">
              We reserve the right to modify these terms at any time. We will notify users of any material changes. Your continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4 text-gray-900 dark:text-white">16. Contact Information</h2>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              For questions about these Terms, please contact us:
            </p>
            <div className="bg-gray-100 dark:bg-gray-800 p-4 rounded-lg text-gray-700 dark:text-gray-300">
              <p><strong>Email:</strong> promtitude@gmail.com</p>
              <p><strong>Phone:</strong> +91 98867 90146</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}