'use client'

import { useState, useEffect } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress-simple'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { 
  UserIcon,
  BriefcaseIcon,
  CalendarIcon,
  ClockIcon,
  StarIcon,
  CheckCircleIcon,
  XCircleIcon,
  AlertCircleIcon,
  AlertTriangleIcon,
  TrendingUpIcon,
  TrendingDownIcon,
  BrainIcon,
  FileTextIcon,
  ShareIcon,
  DownloadIcon,
  SparklesIcon,
  Loader2Icon,
  ArrowLeftIcon
} from 'lucide-react'
import { interviewsApi, InterviewSession } from '@/lib/api/interviews'
import { resumeApi, Resume } from '@/lib/api/client'

export default function InterviewScorecardPage() {
  const params = useParams()
  const router = useRouter()
  const sessionId = params.id as string
  
  const [session, setSession] = useState<InterviewSession | null>(null)
  const [resume, setResume] = useState<Resume | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [scorecard, setScorecard] = useState<any>(null)
  const [isGeneratingReport, setIsGeneratingReport] = useState(false)
  
  // Override setScorecard to add logging
  const setScorecardWithLogging = (newScorecard: any) => {
    if (newScorecard) {
      console.log('=== SETTING SCORECARD ===')
      console.log('isAIGenerated:', newScorecard.isAIGenerated)
      console.log('overallRating:', newScorecard.overallRating)
      console.log('dataSource:', newScorecard.dataSource)
    }
    setScorecard(newScorecard)  // Call the actual setScorecard, not itself!
  }
  
  useEffect(() => {
    if (sessionId) {
      loadScorecardData()
    }
  }, [sessionId])
  
  const loadScorecardData = async () => {
    try {
      setIsLoading(true)
      setError(null)
      
      // Load session data with retry
      let sessionData
      try {
        sessionData = await interviewsApi.getSession(sessionId)
      } catch (sessionError) {
        console.error('First attempt to load session failed:', sessionError)
        // Retry once after a short delay
        await new Promise(resolve => setTimeout(resolve, 1000))
        sessionData = await interviewsApi.getSession(sessionId)
      }
      
      console.log('=== SCORECARD PAGE: Session data loaded ===')
      console.log('Session ID:', sessionId)
      console.log('Session status:', sessionData.status)
      console.log('Session has scorecard?', !!sessionData.scorecard)
      console.log('Session scorecard:', sessionData.scorecard)
      console.log('Session overall_rating:', sessionData.overall_rating)
      console.log('Session recommendation:', sessionData.recommendation)
      setSession(sessionData)
      
      // Load resume data
      const resumeData = await resumeApi.getResume(sessionData.resume_id)
      setResume(resumeData)
      
      // Check if AI scorecard already exists in session data
      // AI scorecard exists if session has scorecard object (generated by AI analysis)
      const hasValidAIScorecard = sessionData.scorecard && 
                                   Object.keys(sessionData.scorecard).length > 0 &&
                                   typeof sessionData.scorecard.overall_rating === 'number'
      
      if (hasValidAIScorecard) {
        console.log('=== AI SCORECARD PATH ===')
        console.log('AI scorecard exists with', Object.keys(sessionData.scorecard).length, 'keys')
        console.log('AI scorecard.overall_rating:', sessionData.scorecard.overall_rating)
        console.log('AI scorecard.overall_rating type:', typeof sessionData.scorecard.overall_rating)
        console.log('Full AI scorecard:', sessionData.scorecard)
        
        // Transform existing scorecard to match frontend format
        const aiScorecard = sessionData.scorecard
        const transformedScorecard = {
          candidateName: `${resumeData.first_name} ${resumeData.last_name}`,
          position: sessionData.job_position,
          interviewDate: sessionData.ended_at ? new Date(sessionData.ended_at).toLocaleDateString() : new Date(sessionData.created_at).toLocaleDateString(),
          duration: sessionData.duration_minutes || 0,
          overallRating: parseFloat(String(aiScorecard.overall_rating || 1.0)),
          recommendation: aiScorecard.recommendation || 'no_hire',
          percentileRank: aiScorecard.percentile_rank || 10,
          ratings: {
            technical: {
              score: aiScorecard.technical_skills ? 
                parseFloat((Object.values(aiScorecard.technical_skills).reduce((sum: number, val: any) => sum + val, 0) / Object.keys(aiScorecard.technical_skills).length).toFixed(1)) : 0,
              breakdown: aiScorecard.technical_skills || {}
            },
            behavioral: {
              score: aiScorecard.soft_skills ? 
                parseFloat((Object.values(aiScorecard.soft_skills).reduce((sum: number, val: any) => sum + val, 0) / Object.keys(aiScorecard.soft_skills).length).toFixed(1)) : 0,
              breakdown: aiScorecard.soft_skills || {}
            },
            cultureFit: aiScorecard.culture_fit || 0
          },
          strengths: aiScorecard.strengths || [],
          concerns: aiScorecard.concerns || [],
          keyTakeaways: aiScorecard.key_takeaways || [],
          nextSteps: aiScorecard.next_steps || [],
          questionPerformance: sessionData.questions?.filter(q => q.response_rating).map(q => ({
            question: q.question_text,
            rating: q.response_rating || 0,
            category: q.category
          })) || [],
          // AI-specific fields
          mismatch_detected: aiScorecard.mismatch_detected || false,
          mismatch_warning: aiScorecard.mismatch_warning || '',
          confidence: aiScorecard.confidence,
          data_quality: aiScorecard.data_quality,
          debug_info: aiScorecard.debug_info,
          isAIGenerated: true
        }
        
        console.log('=== TRANSFORMED AI SCORECARD ===')
        console.log('Transformed overallRating:', transformedScorecard.overallRating)
        console.log('Transformed isAIGenerated:', transformedScorecard.isAIGenerated)
        console.log('Full transformed scorecard:', transformedScorecard)
        setScorecardWithLogging(transformedScorecard)
      } else if (sessionData.questions && sessionData.questions.some(q => q.response_rating !== null && q.response_rating !== undefined)) {
        // Only use human-based scorecard if we have human ratings but no AI scorecard
        console.log('=== HUMAN SCORECARD PATH ===')
        console.log('No AI scorecard found, using human ratings')
        console.log('All questions:', sessionData.questions)
        console.log('Questions with ratings:', sessionData.questions.filter(q => q.response_rating !== null && q.response_rating !== undefined))
        const humanScorecard = generateBasicScorecard(sessionData, resumeData)
        console.log('Human scorecard overallRating:', humanScorecard.overallRating)
        console.log('Human scorecard isAIGenerated:', false)
        console.log('Full human scorecard:', humanScorecard)
        const finalScorecard = {
          ...humanScorecard,
          isAIGenerated: false
        }
        console.log('Final scorecard isAIGenerated:', finalScorecard.isAIGenerated)
        setScorecardWithLogging(finalScorecard)
      } else {
        // No scorecard data available
        console.log('=== NO SCORECARD PATH ===')
        console.log('No AI scorecard and no human ratings found')
        console.log('Session overall_rating:', sessionData.overall_rating)
        console.log('Session recommendation:', sessionData.recommendation)
        
        // Don't assume session.overall_rating is AI data - it could be from human ratings
        // Only show scorecard if we have explicit data
        setScorecardWithLogging(null)
      }
    } catch (error: any) {
      console.error('=== SCORECARD ERROR ===')
      console.error('Failed to load scorecard data:', error)
      console.error('Error type:', error?.constructor?.name)
      console.error('Error message:', error?.message)
      console.error('Error stack:', error?.stack)
      console.error('Error response:', error?.response)
      console.error('Full error object:', error)
      
      if (error.status === 404) {
        setError('Interview session not found. Please check the URL.')
      } else if (error.status === 401 || error.status === 403) {
        setError('Your session has expired. Please log in again.')
        setTimeout(() => {
          router.push('/login')
        }, 2000)
      } else {
        const errorMsg = error?.message || 'Failed to load scorecard data. Please try again.'
        setError(errorMsg)
      }
    } finally {
      setIsLoading(false)
    }
  }
  
  const generateBasicScorecard = (session: InterviewSession, resume: Resume) => {
    // Calculate ratings from questions
    const questions = session.questions || []
    console.log('Session questions:', questions)
    const answeredQuestions = questions.filter(q => q.response_rating)
    console.log('Answered questions:', answeredQuestions)
    const avgRating = answeredQuestions.length > 0
      ? answeredQuestions.reduce((sum, q) => sum + (q.response_rating || 0), 0) / answeredQuestions.length
      : 0
      
    const technicalQuestions = answeredQuestions.filter(q => q.category.toLowerCase() === 'technical')
    const behavioralQuestions = answeredQuestions.filter(q => q.category.toLowerCase() === 'behavioral')
    
    const technicalAvg = technicalQuestions.length > 0
      ? technicalQuestions.reduce((sum, q) => sum + (q.response_rating || 0), 0) / technicalQuestions.length
      : 0
      
    const behavioralAvg = behavioralQuestions.length > 0
      ? behavioralQuestions.reduce((sum, q) => sum + (q.response_rating || 0), 0) / behavioralQuestions.length
      : 0
    
    // Extract skills from questions and calculate skill-specific ratings
    const extractSkillsFromQuestions = (questions: any[]) => {
      const skillRatings: Record<string, { total: number; count: number }> = {}
      
      // Technical skill keywords
      const technicalKeywords = [
        'Python', 'JavaScript', 'React', 'Node.js', 'AWS', 'Docker', 'Kubernetes',
        'Java', 'TypeScript', 'SQL', 'API', 'Database', 'System Design', 'Architecture',
        'Testing', 'CI/CD', 'Git', 'Agile', 'Frontend', 'Backend', 'Full Stack'
      ]
      
      // Behavioral skill keywords
      const behavioralKeywords = [
        'Leadership', 'Communication', 'Teamwork', 'Problem Solving', 'Time Management',
        'Conflict Resolution', 'Adaptability', 'Initiative', 'Collaboration', 'Mentoring'
      ]
      
      questions.forEach(q => {
        if (!q.response_rating) return
        
        const questionLower = q.question_text.toLowerCase()
        const keywords = q.category.toLowerCase() === 'technical' ? technicalKeywords : behavioralKeywords
        
        keywords.forEach(skill => {
          if (questionLower.includes(skill.toLowerCase())) {
            if (!skillRatings[skill]) {
              skillRatings[skill] = { total: 0, count: 0 }
            }
            skillRatings[skill].total += q.response_rating
            skillRatings[skill].count += 1
          }
        })
        
        // If no specific skill found, use general category
        if (Object.keys(skillRatings).length === 0) {
          const generalSkill = q.category.toLowerCase() === 'technical' ? 'Technical Skills' : 'Soft Skills'
          if (!skillRatings[generalSkill]) {
            skillRatings[generalSkill] = { total: 0, count: 0 }
          }
          skillRatings[generalSkill].total += q.response_rating
          skillRatings[generalSkill].count += 1
        }
      })
      
      // Calculate averages
      const breakdown: Record<string, number> = {}
      Object.entries(skillRatings).forEach(([skill, data]) => {
        breakdown[skill] = parseFloat((data.total / data.count).toFixed(1))
      })
      
      return breakdown
    }
    
    const technicalBreakdown = extractSkillsFromQuestions(technicalQuestions)
    const behavioralBreakdown = extractSkillsFromQuestions(behavioralQuestions)
    
    // Generate contextual strengths and concerns based on ratings
    const generateStrengths = () => {
      const strengths = []
      
      // Check technical strengths
      Object.entries(technicalBreakdown).forEach(([skill, rating]) => {
        if (rating >= 4) {
          strengths.push(`Strong ${skill} skills demonstrated`)
        }
      })
      
      // Check behavioral strengths
      Object.entries(behavioralBreakdown).forEach(([skill, rating]) => {
        if (rating >= 4) {
          strengths.push(`Excellent ${skill} abilities`)
        }
      })
      
      // Add from candidate's resume skills if highly rated
      if (avgRating >= 4 && resume.skills && resume.skills.length > 0) {
        strengths.push(`Proven expertise in ${resume.skills.slice(0, 3).join(', ')}`)
      }
      
      // Add experience-based strength
      if (resume.years_experience && resume.years_experience >= 5) {
        strengths.push(`${resume.years_experience} years of relevant industry experience`)
      }
      
      return strengths.length > 0 ? strengths : ['Good overall performance', 'Professional demeanor']
    }
    
    const generateConcerns = () => {
      const concerns = []
      
      // Check technical concerns
      Object.entries(technicalBreakdown).forEach(([skill, rating]) => {
        if (rating < 3) {
          concerns.push(`${skill} skills need improvement`)
        }
      })
      
      // Check behavioral concerns
      Object.entries(behavioralBreakdown).forEach(([skill, rating]) => {
        if (rating < 3) {
          concerns.push(`${skill} could be stronger`)
        }
      })
      
      // Add general concerns if low ratings
      if (avgRating < 3) {
        concerns.push('Overall performance below expectations')
      }
      
      // Check for missing skills from job requirements
      if (session.job_requirements && session.job_requirements.skills) {
        const requiredSkills = session.job_requirements.skills as string[]
        const candidateSkills = resume.skills || []
        const missingSkills = requiredSkills.filter(skill => 
          !candidateSkills.some(cs => cs.toLowerCase().includes(skill.toLowerCase()))
        )
        if (missingSkills.length > 0) {
          concerns.push(`May lack experience with ${missingSkills.slice(0, 2).join(', ')}`)
        }
      }
      
      return concerns.length > 0 ? concerns : ['Further technical assessment recommended']
    }
    
    return {
      candidateName: `${resume.first_name} ${resume.last_name}`,
      position: session.job_position,
      interviewDate: session.ended_at ? new Date(session.ended_at).toLocaleDateString() : new Date(session.created_at).toLocaleDateString(),
      duration: session.duration_minutes || 0,
      overallRating: avgRating.toFixed(1),
      recommendation: session.recommendation || (avgRating >= 4 ? 'hire' : avgRating >= 3 ? 'maybe' : 'no_hire'),
      percentileRank: avgRating >= 4.5 ? 95 : avgRating >= 4 ? 85 : avgRating >= 3.5 ? 70 : avgRating >= 3 ? 50 : 25,
      
      ratings: {
        technical: {
          score: parseFloat(technicalAvg.toFixed(1)),
          breakdown: technicalBreakdown
        },
        behavioral: {
          score: parseFloat(behavioralAvg.toFixed(1)),
          breakdown: behavioralBreakdown
        },
        cultureFit: session.overall_rating || avgRating || 0
      },
      
      strengths: session.strengths && session.strengths.length > 0 ? session.strengths : generateStrengths(),
      
      concerns: session.concerns && session.concerns.length > 0 ? session.concerns : generateConcerns(),
      
      keyTakeaways: (session.preparation_notes?.analysis?.key_talking_points && 
                     Array.isArray(session.preparation_notes.analysis.key_talking_points)) 
                     ? session.preparation_notes.analysis.key_talking_points 
                     : [
                       `${resume.first_name} has ${resume.years_experience || 0} years of experience`,
                       `Current role: ${resume.current_title || 'Not specified'}`,
                       `Key skills include ${resume.skills?.slice(0, 3).join(', ') || 'various technologies'}`
                     ],
      
      nextSteps: avgRating >= 4 
        ? ['Schedule final round interview', 'Check references', 'Prepare offer package']
        : avgRating >= 3
        ? ['Schedule technical assessment', 'Gather additional feedback', 'Compare with other candidates']
        : ['Send polite rejection', 'Keep on file for future opportunities', 'Provide constructive feedback'],
      
      questionPerformance: questions && questions.length > 0 ? questions.map(q => ({
        question: q.question_text,
        rating: q.response_rating || 0,
        category: q.category
      })) : []
    }
  }

  const getRecommendationColor = (recommendation: string) => {
    switch (recommendation) {
      case 'hire': return 'text-green-600 bg-green-100'
      case 'no_hire': return 'text-red-600 bg-red-100'
      default: return 'text-yellow-600 bg-yellow-100'
    }
  }

  const getRecommendationText = (recommendation: string) => {
    switch (recommendation) {
      case 'hire': return 'Recommended for Hire'
      case 'no_hire': return 'Not Recommended'
      default: return 'Requires Further Discussion'
    }
  }

  if (isLoading) {
    return (
      <div className="container mx-auto py-6 px-4 max-w-6xl">
        <div className="flex items-center justify-center min-h-[600px]">
          <div className="text-center">
            <Loader2Icon className="h-8 w-8 animate-spin mx-auto text-muted-foreground" />
            <p className="text-sm text-muted-foreground mt-2">Loading scorecard...</p>
          </div>
        </div>
      </div>
    )
  }
  
  if (error) {
    return (
      <div className="container mx-auto py-6 px-4 max-w-6xl">
        <Alert variant="destructive">
          <AlertCircleIcon className="h-4 w-4" />
          <AlertDescription>
            {error}
          </AlertDescription>
        </Alert>
        <div className="mt-4 space-x-2">
          <Button 
            variant="outline"
            onClick={() => router.push('/dashboard/interviews')}
          >
            <ArrowLeftIcon className="h-4 w-4 mr-2" />
            Back to Interviews
          </Button>
          <Button 
            variant="default"
            onClick={() => loadScorecardData()}
          >
            Try Again
          </Button>
        </div>
      </div>
    )
  }
  
  // Handle case where there's no scorecard data yet
  if (!scorecard && session) {
    return (
      <div className="container mx-auto py-6 px-4 max-w-6xl">
        <Alert>
          <AlertCircleIcon className="h-4 w-4" />
          <AlertDescription>
            <strong>No scorecard available yet</strong>
            <p className="mt-1">
              {session.questions?.some(q => q.response_rating) 
                ? "Human ratings are available. The scorecard will be generated based on these ratings."
                : "Complete the interview and rate candidate responses to generate a scorecard."}
            </p>
          </AlertDescription>
        </Alert>
        <div className="mt-4">
          <Button 
            variant="outline"
            onClick={() => router.push(`/dashboard/interviews/${sessionId}/session`)}
          >
            <ArrowLeftIcon className="h-4 w-4 mr-2" />
            Back to Interview Session
          </Button>
        </div>
      </div>
    )
  }

  return (
    <div className="container mx-auto py-6 px-4 max-w-6xl print-area">
      {/* Header */}
      <div className="mb-6">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold">Interview Scorecard</h1>
            <div className="flex items-center gap-4 mt-2 text-muted-foreground">
              <span className="flex items-center gap-1">
                <UserIcon className="h-4 w-4" />
                {scorecard.candidateName}
              </span>
              <span className="flex items-center gap-1">
                <BriefcaseIcon className="h-4 w-4" />
                {scorecard.position}
              </span>
              <span className="flex items-center gap-1">
                <CalendarIcon className="h-4 w-4" />
                {scorecard.interviewDate}
              </span>
              <span className="flex items-center gap-1">
                <ClockIcon className="h-4 w-4" />
                {scorecard.duration || session?.duration_minutes || 'N/A'} minutes
              </span>
            </div>
          </div>
          <div className="flex gap-2 no-print">
            <Button 
              variant="outline" 
              size="sm"
              onClick={async () => {
                try {
                  // For now, create a shareable summary
                  const shareableText = `
Interview Scorecard - ${scorecard?.candidateName}
Position: ${scorecard?.position}
Date: ${scorecard?.interviewDate}
Overall Rating: ${scorecard?.overallRating}/5
Recommendation: ${scorecard?.recommendation === 'hire' ? 'Recommended for Hire' : 
                   scorecard?.recommendation === 'no_hire' ? 'Not Recommended' : 'Requires Further Discussion'}

Technical Skills: ${scorecard?.ratings?.technical?.score || 0}/5
Behavioral Skills: ${scorecard?.ratings?.behavioral?.score || 0}/5

Key Strengths:
${scorecard?.strengths?.map((s: string) => `• ${s}`).join('\n') || 'None listed'}

Areas of Concern:
${scorecard?.concerns?.map((c: string) => `• ${c}`).join('\n') || 'None listed'}

Next Steps:
${scorecard?.nextSteps?.map((s: string) => `• ${s}`).join('\n') || 'None listed'}

Note: This is a summary. Full scorecard requires system access.
                  `.trim()
                  
                  // Try to use Web Share API first (mobile)
                  if (navigator.share && /mobile|android|iphone/i.test(navigator.userAgent)) {
                    await navigator.share({
                      title: `Interview Scorecard - ${scorecard?.candidateName}`,
                      text: shareableText
                    })
                  } else {
                    // Fallback to clipboard
                    await navigator.clipboard.writeText(shareableText)
                    alert('Scorecard summary copied to clipboard! You can paste it in an email or message.')
                  }
                } catch (err) {
                  console.error('Failed to share:', err)
                  alert('Failed to share scorecard. Please try exporting as PDF instead.')
                }
              }}
            >
              <ShareIcon className="h-4 w-4 mr-2" />
              Share
            </Button>
            <Button 
              variant="outline" 
              size="sm"
              onClick={() => {
                // Generate and download PDF
                window.print()
              }}
            >
              <DownloadIcon className="h-4 w-4 mr-2" />
              Export PDF
            </Button>
          </div>
        </div>
      </div>

      {/* Show both ratings if they differ significantly */}
      {session && scorecard && (
        (() => {
          // Calculate human average rating
          const humanQuestions = session.questions?.filter(q => q.response_rating) || []
          const humanAvgRating = humanQuestions.length > 0
            ? humanQuestions.reduce((sum, q) => sum + (q.response_rating || 0), 0) / humanQuestions.length
            : 0
          
          const aiRating = scorecard.isAIGenerated ? scorecard.overallRating : 0
          const ratingDifference = Math.abs(humanAvgRating - aiRating)
          
          // Always show both ratings if we have AI scorecard and human ratings
          if (scorecard.isAIGenerated && humanQuestions.length > 0) {
            return (
              <Alert className={`mb-6 ${ratingDifference > 1.0 ? 'border-amber-200 bg-amber-50' : ''}`}>
                <AlertCircleIcon className="h-4 w-4" />
                <AlertDescription>
                  <strong>{ratingDifference > 1.0 ? 'Significant Rating Discrepancy' : 'Dual Assessment Results'}</strong>
                  <div className="mt-2 grid grid-cols-2 gap-4">
                    <div className="border rounded-lg p-3 bg-background">
                      <div className="flex items-center gap-2 mb-1">
                        <UserIcon className="h-4 w-4 text-blue-600" />
                        <p className="text-sm font-medium">Human Assessment</p>
                      </div>
                      <p className="text-lg font-bold">{humanAvgRating.toFixed(1)}/5.0</p>
                      <p className="text-xs text-muted-foreground">Based on interviewer ratings</p>
                    </div>
                    <div className="border rounded-lg p-3 bg-background">
                      <div className="flex items-center gap-2 mb-1">
                        <BrainIcon className="h-4 w-4 text-purple-600" />
                        <p className="text-sm font-medium">AI Analysis</p>
                      </div>
                      <p className="text-lg font-bold">{aiRating}/5.0</p>
                      <p className="text-xs text-muted-foreground">Based on transcript analysis</p>
                    </div>
                  </div>
                  {ratingDifference > 1.0 && (
                    <p className="text-sm mt-3">
                      This {ratingDifference.toFixed(1)} point difference warrants further review and discussion.
                    </p>
                  )}
                </AlertDescription>
              </Alert>
            )
          }
          return null
        })()
      )}

      {/* Audio Mismatch Warning */}
      {scorecard.mismatch_detected && (
        <Alert variant="destructive" className="mb-6">
          <AlertTriangleIcon className="h-4 w-4" />
          <AlertDescription>
            <strong>Audio Mismatch Detected</strong>
            <p className="mt-1">{scorecard.mismatch_warning || 'Audio content appears unrelated to interview questions.'}</p>
            <div className="mt-2 text-sm space-y-1">
              <p>This may be due to:</p>
              <ul className="list-disc list-inside ml-2">
                <li>Wrong audio file uploaded</li>
                <li>Technical transcription errors</li>
                <li>Recording issues</li>
                <li>Manual transcript formatting issues (ensure proper [interviewer]: and [candidate]: tags)</li>
              </ul>
            </div>
            <div className="mt-3 pt-3 border-t border-red-200">
              <p className="text-sm">
                <strong>AI Confidence:</strong> {scorecard.confidence || 'Low'}% | 
                <strong className="ml-2">Data Quality:</strong> {scorecard.data_quality || 'Mismatch'}
              </p>
              {scorecard.debug_info && (
                <p className="text-xs mt-1 text-red-600">
                  Debug: {scorecard.debug_info.relevant_responses || 0}/{scorecard.debug_info.total_responses || 0} responses matched expected content
                </p>
              )}
            </div>
          </AlertDescription>
        </Alert>
      )}

      {/* Overall Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <Card>
          <CardContent className="p-6">
            <div className="text-center">
              <div className="flex items-center justify-center gap-2 mb-2">
                {(scorecard.isAIGenerated && session?.scorecard) ? (
                  <BrainIcon className="h-6 w-6 text-purple-600" />
                ) : (
                  <UserIcon className="h-6 w-6 text-blue-600" />
                )}
                <div className="text-4xl font-bold">{scorecard.overallRating}/5</div>
              </div>
              <div className="flex justify-center mb-2">
                {[1, 2, 3, 4, 5].map((star) => (
                  <StarIcon
                    key={star}
                    className={`h-5 w-5 ${
                      star <= Math.floor(scorecard.overallRating)
                        ? 'fill-yellow-400 text-yellow-400'
                        : 'text-gray-300'
                    }`}
                  />
                ))}
              </div>
              <p className="text-sm font-medium text-foreground">
                {/* Extra safeguard: never show AI if no scorecard data in session */}
                {(scorecard.isAIGenerated && session?.scorecard) ? 'AI Analysis Rating' : 'Human Assessment Rating'}
              </p>
              <p className="text-xs text-muted-foreground mt-1">
                {(scorecard.isAIGenerated && session?.scorecard) ? 'Based on transcript analysis' : 'Based on interviewer ratings'}
              </p>
              {/* Debug info - only show in development */}
              {false && process.env.NODE_ENV === 'development' && (
                <div className="mt-2 pt-2 border-t text-xs text-muted-foreground">
                  <p>Source: {scorecard.isAIGenerated ? 'session.scorecard' : 'calculated from questions'}</p>
                  <p>isAIGenerated: {String(scorecard.isAIGenerated)}</p>
                  <p>session.scorecard exists: {String(!!session?.scorecard)}</p>
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="text-center">
              <Badge 
                className={`text-lg px-4 py-2 mb-2 ${getRecommendationColor(scorecard.recommendation)}`}
              >
                {getRecommendationText(scorecard.recommendation)}
              </Badge>
              <p className="text-sm text-muted-foreground mt-2">Interview Decision</p>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-6">
            <div className="text-center">
              <div className="text-4xl font-bold mb-2">{scorecard.percentileRank}%</div>
              <Progress value={scorecard.percentileRank} className="mb-2" />
              <p className="text-sm text-muted-foreground">Percentile Ranking</p>
            </div>
          </CardContent>
        </Card>
      </div>


      {/* Detailed Assessment */}
      <Tabs defaultValue="ratings" className="space-y-6">
        <TabsList className="grid w-full grid-cols-4 tabs-navigation">
          <TabsTrigger value="ratings">Ratings</TabsTrigger>
          <TabsTrigger value="strengths">Strengths & Concerns</TabsTrigger>
          <TabsTrigger value="performance">Question Performance</TabsTrigger>
          <TabsTrigger value="ai-insights">AI Insights</TabsTrigger>
        </TabsList>

        <TabsContent value="ratings" className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Technical Skills */}
            <Card>
              <CardHeader>
                <CardTitle>Technical Skills</CardTitle>
                <div className="text-2xl font-bold">
                  {scorecard.ratings?.technical?.score || '0'}/5
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {scorecard.ratings?.technical?.breakdown ? (
                    Object.entries(scorecard.ratings.technical.breakdown).map(([skill, rating]: [string, any]) => (
                      <div key={skill}>
                        <div className="flex justify-between mb-1">
                          <span className="text-sm">{skill}</span>
                          <span className="text-sm font-medium">{rating}/5</span>
                        </div>
                        <Progress value={rating * 20} />
                      </div>
                    ))
                  ) : (
                    <p className="text-sm text-muted-foreground">
                      Technical skills will be evaluated during the interview
                    </p>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Behavioral Skills */}
            <Card>
              <CardHeader>
                <CardTitle>Behavioral Skills</CardTitle>
                <div className="text-2xl font-bold">
                  {scorecard.ratings?.behavioral?.score || '0'}/5
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {scorecard.ratings?.behavioral?.breakdown ? (
                    Object.entries(scorecard.ratings.behavioral.breakdown).map(([skill, rating]: [string, any]) => (
                      <div key={skill}>
                        <div className="flex justify-between mb-1">
                          <span className="text-sm">{skill}</span>
                          <span className="text-sm font-medium">{rating}/5</span>
                        </div>
                        <Progress value={rating * 20} />
                      </div>
                    ))
                  ) : (
                    <p className="text-sm text-muted-foreground">
                      Behavioral skills will be evaluated during the interview
                    </p>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Culture Fit */}
          <Card>
            <CardHeader>
              <CardTitle>Culture Fit Assessment</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <Progress value={(scorecard.ratings?.cultureFit || 0) * 20} className="h-3" />
                </div>
                <div className="ml-4 text-2xl font-bold">{scorecard.ratings?.cultureFit || 0}/5</div>
              </div>
              <p className="text-sm text-muted-foreground mt-2">
                Based on alignment with company values and team dynamics
              </p>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="strengths" className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUpIcon className="h-5 w-5 text-green-600" />
                  Key Strengths
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {scorecard.strengths && scorecard.strengths.length > 0 ? (
                    scorecard.strengths.map((strength: string, idx: number) => (
                      <li key={idx} className="flex items-start gap-2">
                        <CheckCircleIcon className="h-5 w-5 text-green-600 mt-0.5 flex-shrink-0" />
                        <span>{strength}</span>
                      </li>
                    ))
                  ) : (
                    <li className="text-sm text-muted-foreground">No strengths identified yet</li>
                  )}
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <AlertCircleIcon className="h-5 w-5 text-amber-600" />
                  Areas of Concern
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {scorecard.concerns && scorecard.concerns.length > 0 ? (
                    scorecard.concerns.map((concern: string, idx: number) => (
                      <li key={idx} className="flex items-start gap-2">
                        <AlertCircleIcon className="h-5 w-5 text-amber-600 mt-0.5 flex-shrink-0" />
                        <span>{concern}</span>
                      </li>
                    ))
                  ) : (
                    <li className="text-sm text-muted-foreground">No concerns identified yet</li>
                  )}
                </ul>
              </CardContent>
            </Card>
          </div>

          {/* Key Takeaways */}
          <Card>
            <CardHeader>
              <CardTitle>Key Takeaways</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {scorecard.keyTakeaways && scorecard.keyTakeaways.length > 0 ? (
                  scorecard.keyTakeaways.map((takeaway: string, idx: number) => (
                    <li key={idx} className="flex items-start gap-2">
                      <BrainIcon className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                      <span>{takeaway}</span>
                    </li>
                  ))
                ) : (
                  <li className="text-sm text-muted-foreground">Key takeaways will be available after interview completion</li>
                )}
              </ul>
            </CardContent>
          </Card>

          {/* Next Steps */}
          <Card>
            <CardHeader>
              <CardTitle>Recommended Next Steps</CardTitle>
            </CardHeader>
            <CardContent>
              <ol className="space-y-2">
                {scorecard.nextSteps && scorecard.nextSteps.length > 0 ? (
                  scorecard.nextSteps.map((step: string, idx: number) => (
                    <li key={idx} className="flex items-start gap-2">
                      <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary text-primary-foreground text-xs flex items-center justify-center mt-0.5">
                        {idx + 1}
                      </span>
                      <span>{step}</span>
                    </li>
                  ))
                ) : (
                  <li className="text-sm text-muted-foreground">Next steps will be determined after interview completion</li>
                )}
              </ol>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="performance" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Question-by-Question Performance</CardTitle>
              <CardDescription>
                How the candidate performed on each interview question
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {scorecard.questionPerformance && scorecard.questionPerformance.length > 0 ? (
                  scorecard.questionPerformance.map((q: any, idx: number) => (
                    <div key={idx} className="border rounded-lg p-4">
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex-1">
                          <h4 className="font-medium line-clamp-2">{q.question}</h4>
                          <Badge variant="outline" className="mt-1">{q.category}</Badge>
                        </div>
                        <div className="text-right">
                          <div className="text-2xl font-bold">
                            {q.rating > 0 ? `${q.rating}/5` : 'Not rated'}
                          </div>
                          {q.rating > 0 && (
                            <div className="flex justify-end mt-1">
                              {[1, 2, 3, 4, 5].map((star) => (
                                <StarIcon
                                  key={star}
                                  className={`h-4 w-4 ${
                                    star <= q.rating
                                      ? 'fill-yellow-400 text-yellow-400'
                                      : 'text-gray-300'
                                  }`}
                                />
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    No questions have been rated yet
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="ai-insights" className="space-y-6">
          {/* Only show AI content header if we actually have AI analysis */}
          {scorecard?.isAIGenerated ? (
            <Alert>
              <SparklesIcon className="h-4 w-4" />
              <AlertDescription>
                AI-generated insights based on interview performance and candidate profile
              </AlertDescription>
            </Alert>
          ) : null}

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BrainIcon className="h-5 w-5" />
                {scorecard?.isAIGenerated ? 'AI Analysis' : 'Interview Insights'}
              </CardTitle>
              <CardDescription>
                {scorecard?.isAIGenerated 
                  ? 'Comprehensive AI evaluation based on interview responses and candidate profile'
                  : 'Assessment insights and recommendations'}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Debug: Check scorecard state */}
              {process.env.NODE_ENV === 'development' && (
                <div className="text-xs text-muted-foreground mb-2">
                  Debug: session.scorecard exists: {String(!!session?.scorecard)}, 
                  scorecard.isAIGenerated: {String(scorecard?.isAIGenerated)},
                  hasValidAIScorecard check would be: {String(!!session?.scorecard && Object.keys(session.scorecard).length > 0)}
                </div>
              )}
              {scorecard?.isAIGenerated ? (
                <>
                  <div>
                    <h4 className="font-medium mb-2">Post-Interview Summary</h4>
                    <p className="text-sm text-muted-foreground">
                      {/* Show actual candidate performance summary from the interview */}
                      {(() => {
                        const rating = scorecard?.overallRating || 0;
                        const strengths = scorecard?.strengths || [];
                        const position = scorecard?.position || 'this position';
                        
                        if (rating >= 4.5) {
                          return `${scorecard?.candidateName} demonstrated exceptional performance during the interview, showing strong technical expertise and excellent communication skills. Their responses reflected deep understanding and practical experience relevant to ${position}.`;
                        } else if (rating >= 3.5) {
                          return `${scorecard?.candidateName} showed solid capabilities during the interview with good technical knowledge and communication skills. They demonstrated competence in key areas required for ${position}, with some areas for potential growth.`;
                        } else if (rating >= 2.5) {
                          return `${scorecard?.candidateName} displayed mixed performance during the interview. While showing potential in some areas, there were notable gaps in experience or skills required for ${position}.`;
                        } else {
                          return `${scorecard?.candidateName}'s interview performance indicated significant gaps in the skills and experience required for ${position}. Further evaluation or development would be needed.`;
                        }
                      })()}
                    </p>
                  </div>
                  
                  {scorecard && (
                    <div className="border-l-4 border-purple-200 pl-4">
                      <h4 className="font-medium mb-2 flex items-center gap-2">
                        Interview Performance Assessment
                        <span className="text-xs text-muted-foreground font-normal">
                          (Based on actual interview responses)
                        </span>
                      </h4>
                      <div className="flex items-center gap-3 mb-2">
                        <div className="flex items-center gap-2">
                          <p className="text-lg font-semibold">
                            {scorecard.overallRating}/5
                          </p>
                          <div className="flex gap-0.5">
                            {[1, 2, 3, 4, 5].map((star) => (
                              <StarIcon
                                key={star}
                                className={`h-4 w-4 ${
                                  star <= Math.round(scorecard.overallRating)
                                    ? 'fill-purple-400 text-purple-400'
                                    : 'fill-gray-200 text-gray-200'
                                }`}
                              />
                            ))}
                          </div>
                        </div>
                        <Badge variant="secondary" className="text-xs">
                          {scorecard.isAIGenerated ? 'AI Analysis' : 'Human Assessment'}
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {/* Show technical skills demonstrated */}
                        {scorecard.ratings?.technical?.breakdown && Object.keys(scorecard.ratings.technical.breakdown).length > 0 && (
                          <>
                            Demonstrated proficiency in: {Object.entries(scorecard.ratings.technical.breakdown)
                              .filter(([_, rating]: [string, any]) => rating >= 4)
                              .map(([skill, _]: [string, any]) => skill)
                              .join(', ') || 'various technical areas'}
                          </>
                        )}
                      </p>
                    </div>
                  )}
                  
                  {/* Show specific insights from the interview */}
                  {session?.preparation_notes?.transcript_insights && (
                    <div>
                      <h4 className="font-medium mb-2">Interview Insights</h4>
                      <ul className="text-sm text-muted-foreground space-y-1">
                        {session.preparation_notes.transcript_insights.skills_identified && 
                         session.preparation_notes.transcript_insights.skills_identified.length > 0 && (
                          <li>• Technologies discussed: {session.preparation_notes.transcript_insights.skills_identified.slice(0, 5).join(', ')}</li>
                        )}
                        {session.preparation_notes.transcript_insights.total_questions > 0 && (
                          <li>• Answered {session.preparation_notes.transcript_insights.total_questions} questions with average rating of {session.preparation_notes.transcript_insights.average_rating.toFixed(1)}/5</li>
                        )}
                        {scorecard?.strengths && scorecard.strengths.length > 0 && (
                          <li>• Key strength: {scorecard.strengths[0]}</li>
                        )}
                      </ul>
                    </div>
                  )}
                </>
              ) : scorecard && !scorecard.isAIGenerated ? (
                <>
                  {/* Show human assessment when scorecard exists but is not AI-generated */}
                  <div className="space-y-4">
                    <Alert>
                      <AlertCircleIcon className="h-4 w-4" />
                      <AlertDescription>
                        <strong>Human assessment completed</strong>
                        <p className="mt-1">This scorecard is based on interviewer ratings. To get AI-powered insights, upload an audio recording or enter a transcript of the interview.</p>
                      </AlertDescription>
                    </Alert>
                    
                    {/* Human assessment summary */}
                    <div>
                      <h4 className="font-medium mb-2">Human Assessment Summary</h4>
                      <div className="border-l-4 border-blue-200 pl-4">
                          <div className="flex items-center gap-3 mb-2">
                            <div className="flex items-center gap-2">
                              <UserIcon className="h-5 w-5 text-blue-600" />
                              <p className="text-lg font-semibold">
                                {scorecard.overallRating}/5
                              </p>
                              <div className="flex gap-0.5">
                                {[1, 2, 3, 4, 5].map((star) => (
                                  <StarIcon
                                    key={star}
                                    className={`h-4 w-4 ${
                                      star <= Math.round(scorecard.overallRating)
                                        ? 'fill-blue-400 text-blue-400'
                                        : 'fill-gray-200 text-gray-200'
                                    }`}
                                  />
                                ))}
                              </div>
                            </div>
                            <Badge variant="secondary" className="text-xs">
                              Interviewer Rating
                            </Badge>
                          </div>
                          <p className="text-sm text-muted-foreground">
                            Based on {scorecard.questionPerformance?.filter((q: any) => q.rating > 0).length || 0} rated questions
                          </p>
                        </div>
                      
                      {/* Show key points from human assessment */}
                      {(scorecard.strengths?.length > 0 || scorecard.concerns?.length > 0) && (
                        <div>
                          <h4 className="font-medium mb-2">Assessment Highlights</h4>
                          <div className="text-sm text-muted-foreground space-y-2">
                            {scorecard.strengths?.length > 0 && (
                              <div>
                                <span className="font-medium">Strengths:</span>
                                <ul className="ml-4 mt-1">
                                  {scorecard.strengths.slice(0, 3).map((strength: string, idx: number) => (
                                    <li key={idx}>• {strength}</li>
                                  ))}
                                </ul>
                              </div>
                            )}
                            {scorecard.concerns?.length > 0 && (
                              <div>
                                <span className="font-medium">Areas to explore:</span>
                                <ul className="ml-4 mt-1">
                                  {scorecard.concerns.slice(0, 2).map((concern: string, idx: number) => (
                                    <li key={idx}>• {concern}</li>
                                  ))}
                                </ul>
                              </div>
                            )}
                          </div>
                        </div>
                      )}
                      
                      <div className="pt-4 border-t">
                        <p className="text-sm text-muted-foreground">
                          💡 <strong>Tip:</strong> For deeper insights and AI-powered analysis, consider uploading the interview recording or transcript.
                        </p>
                      </div>
                    </div>
                  </div>
                </>
              ) : session?.preparation_notes?.analysis ? (
                <>
                  {/* Show pre-interview assessment when no scorecard exists yet */}
                  <Alert>
                    <AlertCircleIcon className="h-4 w-4" />
                    <AlertDescription>
                      Showing pre-interview assessment. Complete the interview to see post-interview insights.
                    </AlertDescription>
                  </Alert>
                  <div>
                    <h4 className="font-medium mb-2">Pre-Interview Assessment</h4>
                    <p className="text-sm text-muted-foreground">
                      {session.preparation_notes.analysis.candidate_summary?.brief || 
                       'Initial assessment based on resume analysis.'}
                    </p>
                  </div>
                </>
              ) : (
                <>
                  {/* Default case when no data is available */}
                  <Alert>
                    <AlertCircleIcon className="h-4 w-4" />
                    <AlertDescription>
                      AI insights will be generated based on the completed interview performance. 
                      Complete all interview questions and ratings to get comprehensive AI analysis.
                    </AlertDescription>
                  </Alert>
                </>
              )}
            </CardContent>
          </Card>

          {session?.status === 'completed' && (
            <Card>
              <CardHeader>
                <CardTitle>Generate Full AI Report</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-center py-8">
                  <SparklesIcon className="h-12 w-12 mx-auto mb-4 text-primary" />
                  <p className="mb-4">Get comprehensive AI analysis of this interview</p>
                  <Button 
                    onClick={async () => {
                      try {
                        setIsLoading(true)
                        const scorecardData = await interviewsApi.generateScorecard(sessionId)
                        
                        // Transform API response to match frontend format
                        const transformedScorecard = {
                          ...scorecardData,
                          candidateName: scorecardData.candidate_name,
                          position: scorecardData.position,
                          interviewDate: scorecardData.interview_date,
                          duration: session?.duration_minutes || 0,
                          overallRating: scorecardData.overall_rating,
                          recommendation: scorecardData.recommendation,
                          percentileRank: scorecardData.percentile_rank,
                          ratings: {
                            technical: {
                              score: scorecardData.technical_skills ? 
                                parseFloat((Object.values(scorecardData.technical_skills).reduce((sum: number, val: any) => sum + val, 0) / Object.keys(scorecardData.technical_skills).length).toFixed(1)) : 0,
                              breakdown: scorecardData.technical_skills || {}
                            },
                            behavioral: {
                              score: scorecardData.soft_skills ? 
                                parseFloat((Object.values(scorecardData.soft_skills).reduce((sum: number, val: any) => sum + val, 0) / Object.keys(scorecardData.soft_skills).length).toFixed(1)) : 0,
                              breakdown: scorecardData.soft_skills || {}
                            },
                            cultureFit: scorecardData.culture_fit || 0
                          },
                          strengths: scorecardData.strengths || [],
                          concerns: scorecardData.concerns || [],
                          keyTakeaways: scorecardData.key_takeaways || [],
                          nextSteps: scorecardData.next_steps || [],
                          questionPerformance: session?.questions?.filter((q: any) => q.response_rating).map((q: any) => ({
                            question: q.question_text,
                            rating: q.response_rating || 0,
                            category: q.category
                          })) || []
                        }
                        
                        setScorecardWithLogging(transformedScorecard)
                        setIsLoading(false)
                        
                        // Show success message
                        alert('AI Report generated successfully!')
                      } catch (err) {
                        console.error('Failed to generate report:', err)
                        setIsLoading(false)
                        alert('Failed to generate AI report. Please try again.')
                      }
                    }}
                    disabled={isLoading}
                  >
                    {isLoading ? (
                      <>
                        <Loader2Icon className="h-4 w-4 mr-2 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <SparklesIcon className="h-4 w-4 mr-2" />
                        Generate AI Report
                      </>
                    )}
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>

      {/* Action Buttons */}
      <div className="flex justify-center gap-4 mt-8 no-print">
        <Button variant="outline" onClick={() => router.push('/dashboard/interviews')}>
          Back to Interviews
        </Button>
        <Button
          onClick={async () => {
            if (!resume || !session) {
              alert('Unable to schedule next round. Missing information.')
              return
            }
            
            try {
              setIsGeneratingReport(true)
              setError(null)
              
              // Call the new API endpoint to schedule next round
              const response = await interviewsApi.scheduleNextRound(session.id)
              
              if (response && response.session_id) {
                // Navigate directly to the new interview session
                router.push(`/dashboard/interviews/${response.session_id}/session`)
              } else {
                throw new Error('Failed to schedule next round')
              }
            } catch (error: any) {
              console.error('Failed to schedule next round:', error)
              const errorMessage = error?.detail || error?.message || 'Failed to schedule next round'
              alert(typeof errorMessage === 'string' ? errorMessage : 'Failed to schedule next round')
            } finally {
              setIsGeneratingReport(false)
            }
          }}
          disabled={!resume || scorecard?.recommendation === 'no_hire' || isGeneratingReport}
        >
          {isGeneratingReport ? (
            <>
              <Loader2Icon className="h-4 w-4 mr-2 animate-spin" />
              Scheduling...
            </>
          ) : (
            'Schedule Next Round'
          )}
        </Button>
      </div>
    </div>
  )
}